import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { projectName, prompt, code } = await req.json();

  try {
    // 1. Create GitHub repo
    const githubRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: projectName,
        description: prompt.substring(0, 100),
        private: false,
        auto_init: true,
      }),
    });

    if (!githubRes.ok) {
      throw new Error("GitHub error");
    }

    const githubData = await githubRes.json();
    const githubUrl = githubData.html_url;

    // 2. Upload to GitHub
    await fetch(
      `https://api.github.com/repos/${githubData.owner.login}/${projectName}/contents/index.html`,
      {
        method: "PUT",
        headers: {
          Authorization: `token ${process.env.GITHUB_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Initial commit - Generated by PromptMB AI",
          content: Buffer.from(code).toString("base64"),
        }),
      }
    );

    // 3. Deploy to Vercel
    const vercelRes = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: projectName,
        gitSource: {
          type: "github",
          repo: `${githubData.owner.login}/${projectName}`,
          ref: "main",
        },
      }),
    });

    if (!vercelRes.ok) {
      throw new Error("Vercel error");
    }

    const vercelData = await vercelRes.json();
    const vercelUrl = `https://${vercelData.projectName}.vercel.app`;

    // 4. Save to Supabase
    const { error: dbError } = await supabase.from("projects").insert({
      user_id: session.user.id,
      name: projectName,
      prompt,
      github_url: githubUrl,
      vercel_url: vercelUrl,
      status: "live",
    });

    if (dbError) throw dbError;

    return NextResponse.json({
      success: true,
      vercelUrl,
    });
  } catch (error: any) {
    console.error("Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to deploy" },
      { status: 500 }
    );
  }
}
